In [1]:
import numpy as np

In [ ]:
#===================================================================================
# Slicing
#===================================================================================

#--------------------------------array slicing in one dimension---------------------------------------
arr = np.array([1, 2, 3, 4, 5])
# arr[Start:Stop:Step]
print(arr[1:4])  # Output: [2 3 4]
print(arr[2:-1])  # Output: [3 4 5]
print(arr[::2])  # Output: [1 3 5]
print(arr[::-1])  # Output: [5 4 3 2 1]

# You can also use () to slice arrays
# this is useful when you want to slice multiple elements at once
print(arr[(0, 2, 4)])  # Output: [1 3 5]

# You can assign values to slices of an array
arr[1:4] = 0
print(arr)  # Output: [1 0 0 0 5]



#--------------------------------array slicing in two dimensions---------------------------------------
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
# arr[StartRow:StopRow:StepRow, StartCol:StopCol:StepCol]
print(arr[0:2, 1:3])  # Output: [[2 3]
#                                [5 6]]
print(arr[::2, ::2])  # Output: [[1 3]
#                                [7 9]]
print(arr[::-1, ::-1])  # Output: [[9 8 7]
#                                  [6 5 4]
#                                  [3 2 1]]
print(arr[1:, 0])  # Output: [4 7]
print(arr[:, 1])  # Output: [2 5 8]

# You can also use () to slice arrays
# this is useful when you want to slice multiple rows or columns at once
print(arr[:, (0, 2)])  # Output: [[1 3]
#                                 [4 6]
#                                 [7 9]]
print(arr[(0, 2), :])  # Output: [[1 2 3]
#                                 [7 8 9]]

# you can assign values to slices of an array
arr[0:2, 1:3] = 0
print(arr)  # Output: [[1 0 0]
#                      [4 0 0]
#                      [7 8 9]]

[2 3 4]
[3 4]
[1 3 5]
[5 4 3 2 1]
[[2 3]
 [5 6]]
[[1 3]
 [7 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[4 7]
[2 5 8]
[[1 3]
 [4 6]
 [7 9]]
[[1 2 3]
 [7 8 9]]
[[1 0 0]
 [4 0 0]
 [7 8 9]]
